/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SocialRouteImport } from './routes/social'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RoastRouteImport } from './routes/roast'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DamageRouteImport } from './routes/damage'
import { Route as ControlRouteImport } from './routes/control'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RoastRoute = RoastRouteImport.update({
  id: '/roast',
  path: '/roast',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DamageRoute = DamageRouteImport.update({
  id: '/damage',
  path: '/damage',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRoute = ControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/control': typeof ControlRoute
  '/damage': typeof DamageRoute
  '/home': typeof HomeRoute
  '/insights': typeof InsightsRoute
  '/intelligence': typeof IntelligenceRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/roast': typeof RoastRoute
  '/signup': typeof SignupRoute
  '/social': typeof SocialRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/control': typeof ControlRoute
  '/damage': typeof DamageRoute
  '/home': typeof HomeRoute
  '/insights': typeof InsightsRoute
  '/intelligence': typeof IntelligenceRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/roast': typeof RoastRoute
  '/signup': typeof SignupRoute
  '/social': typeof SocialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/control': typeof ControlRoute
  '/damage': typeof DamageRoute
  '/home': typeof HomeRoute
  '/insights': typeof InsightsRoute
  '/intelligence': typeof IntelligenceRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/roast': typeof RoastRoute
  '/signup': typeof SignupRoute
  '/social': typeof SocialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/control'
    | '/damage'
    | '/home'
    | '/insights'
    | '/intelligence'
    | '/login'
    | '/profile'
    | '/roast'
    | '/signup'
    | '/social'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/control'
    | '/damage'
    | '/home'
    | '/insights'
    | '/intelligence'
    | '/login'
    | '/profile'
    | '/roast'
    | '/signup'
    | '/social'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/control'
    | '/damage'
    | '/home'
    | '/insights'
    | '/intelligence'
    | '/login'
    | '/profile'
    | '/roast'
    | '/signup'
    | '/social'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ControlRoute: typeof ControlRoute
  DamageRoute: typeof DamageRoute
  HomeRoute: typeof HomeRoute
  InsightsRoute: typeof InsightsRoute
  IntelligenceRoute: typeof IntelligenceRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RoastRoute: typeof RoastRoute
  SignupRoute: typeof SignupRoute
  SocialRoute: typeof SocialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roast': {
      id: '/roast'
      path: '/roast'
      fullPath: '/roast'
      preLoaderRoute: typeof RoastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/damage': {
      id: '/damage'
      path: '/damage'
      fullPath: '/damage'
      preLoaderRoute: typeof DamageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control': {
      id: '/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof ControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ControlRoute: ControlRoute,
  DamageRoute: DamageRoute,
  HomeRoute: HomeRoute,
  InsightsRoute: InsightsRoute,
  IntelligenceRoute: IntelligenceRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RoastRoute: RoastRoute,
  SignupRoute: SignupRoute,
  SocialRoute: SocialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
