export const queryKeys = {
  dashboard: ["dashboard"] as const,
  activity: ["activity"] as const,
  profile: ["profile"] as const,
  achievements: ["achievements"] as const,
  analytics: ["analytics"] as const,
  highlights: ["highlights"] as const,
  apps: ["apps"] as const,
  nearby: ["nearby"] as const,
  smokeDna: ["intelligence", "smoke-dna"] as const,
  smokeReplayHistory: ["intelligence", "smoke-replay", "history"] as const,
  smokeReplayMonthly: (year: number, month: number) => ["intelligence", "smoke-replay", "monthly", year, month] as const,
  smokeReplayYearly: (year: number) => ["intelligence", "smoke-replay", "yearly", year] as const,
  cravingHistory: ["intelligence", "craving-history"] as const,
  cravingLive: ["intelligence", "craving-live"] as const,
  voiceCommands: ["intelligence", "voice-commands"] as const,
  scannerHistory: ["control", "scanner-history"] as const,
  ritualSessions: ["control", "ritual-sessions"] as const,
  emergencySessions: ["control", "emergency-sessions"] as const,
  favoriteStores: ["nearby", "favorite-stores"] as const,
};
